# Generated by Django 4.1.7 on 2023-03-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameOdds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_id', models.TextField(max_length=100)),
                ('game_id', models.IntegerField()),
                ('team', models.TextField(max_length=200)),
                ('line', models.DecimalField(decimal_places=2, max_digits=6)),
                ('book', models.TextField(max_length=50)),
                ('home_team', models.TextField(max_length=200)),
                ('away_team', models.TextField(max_length=200)),
                ('start_time', models.DateTimeField()),
                ('league', models.TextField(max_length=15)),
                ('line_update', models.DateTimeField()),
            ],
        ),
    ]
